/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as DesignSystemIndexRouteImport } from './pages/design-system/index'
import { Route as AuthIndexRouteImport } from './pages/_auth/index'
import { Route as AppFeedIndexRouteImport } from './pages/_app/feed/index'
import { Route as AppFavoritesIndexRouteImport } from './pages/_app/favorites/index'
import { Route as AppWriterIndexRouteImport } from './pages/_app/$writer/index'
import { Route as AppMeLibraryRouteImport } from './pages/_app/me/library'
import { Route as AppMeFollowingRouteImport } from './pages/_app/me/following'
import { Route as AppWriterPostIdIndexRouteImport } from './pages/_app/$writer/$postId/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIndexRoute = DesignSystemIndexRouteImport.update({
  id: '/design-system/',
  path: '/design-system/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/_auth/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeedIndexRoute = AppFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWriterIndexRoute = AppWriterIndexRouteImport.update({
  id: '/$writer/',
  path: '/$writer/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMeLibraryRoute = AppMeLibraryRouteImport.update({
  id: '/me/library',
  path: '/me/library',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMeFollowingRoute = AppMeFollowingRouteImport.update({
  id: '/me/following',
  path: '/me/following',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWriterPostIdIndexRoute = AppWriterPostIdIndexRouteImport.update({
  id: '/$writer/$postId/',
  path: '/$writer/$postId/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/me/following': typeof AppMeFollowingRoute
  '/me/library': typeof AppMeLibraryRoute
  '/$writer/': typeof AppWriterIndexRoute
  '/favorites/': typeof AppFavoritesIndexRoute
  '/feed/': typeof AppFeedIndexRoute
  '/$writer/$postId/': typeof AppWriterPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/design-system': typeof DesignSystemIndexRoute
  '/me/following': typeof AppMeFollowingRoute
  '/me/library': typeof AppMeLibraryRoute
  '/$writer': typeof AppWriterIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
  '/feed': typeof AppFeedIndexRoute
  '/$writer/$postId': typeof AppWriterPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/_app/me/following': typeof AppMeFollowingRoute
  '/_app/me/library': typeof AppMeLibraryRoute
  '/_app/$writer/': typeof AppWriterIndexRoute
  '/_app/favorites/': typeof AppFavoritesIndexRoute
  '/_app/feed/': typeof AppFeedIndexRoute
  '/_app/$writer/$postId/': typeof AppWriterPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system/'
    | '/me/following'
    | '/me/library'
    | '/$writer/'
    | '/favorites/'
    | '/feed/'
    | '/$writer/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/me/following'
    | '/me/library'
    | '/$writer'
    | '/favorites'
    | '/feed'
    | '/$writer/$postId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth/'
    | '/design-system/'
    | '/_app/me/following'
    | '/_app/me/library'
    | '/_app/$writer/'
    | '/_app/favorites/'
    | '/_app/feed/'
    | '/_app/$writer/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  DesignSystemIndexRoute: typeof DesignSystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/': {
      id: '/design-system/'
      path: '/design-system'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/feed/': {
      id: '/_app/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof AppFeedIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/favorites/': {
      id: '/_app/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$writer/': {
      id: '/_app/$writer/'
      path: '/$writer'
      fullPath: '/$writer/'
      preLoaderRoute: typeof AppWriterIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/me/library': {
      id: '/_app/me/library'
      path: '/me/library'
      fullPath: '/me/library'
      preLoaderRoute: typeof AppMeLibraryRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/me/following': {
      id: '/_app/me/following'
      path: '/me/following'
      fullPath: '/me/following'
      preLoaderRoute: typeof AppMeFollowingRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$writer/$postId/': {
      id: '/_app/$writer/$postId/'
      path: '/$writer/$postId'
      fullPath: '/$writer/$postId/'
      preLoaderRoute: typeof AppWriterPostIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppMeFollowingRoute: typeof AppMeFollowingRoute
  AppMeLibraryRoute: typeof AppMeLibraryRoute
  AppWriterIndexRoute: typeof AppWriterIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
  AppFeedIndexRoute: typeof AppFeedIndexRoute
  AppWriterPostIdIndexRoute: typeof AppWriterPostIdIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppMeFollowingRoute: AppMeFollowingRoute,
  AppMeLibraryRoute: AppMeLibraryRoute,
  AppWriterIndexRoute: AppWriterIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
  AppFeedIndexRoute: AppFeedIndexRoute,
  AppWriterPostIdIndexRoute: AppWriterPostIdIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  DesignSystemIndexRoute: DesignSystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
